### Déployer le frontend
Duration: 5:00

Un pod Kubernetes est un groupe de conteneurs, liés ensemble à des fins d'administration et de mise en réseau. Il peut contenir un ou plusieurs conteneurs. Tous les conteneurs d'un même pod partageront la même interface réseau, la même adresse IP, les mêmes volumes, etc. Tous les conteneurs d'une même instance de pod vivront et mourront ensemble. C'est particulièrement utile lorsque vous avez, par exemple, un conteneur qui exécute l'application et un autre conteneur qui interroge périodiquement les journaux/métriques du conteneur d'application.

Vous pouvez démarrer un seul pod dans Kubernetes en créant une ressource de pod. Cependant, un pod créé de cette manière serait connu sous le nom de lien : https://kubernetes.io/docs/concepts/configuration/overview/#naked-pods-vs-replication-controllers-and-jobs[Naked Pod]. Cependant, si un pod tombe dans ce cas, il ne sera pas redémarré par Kubernetes. La meilleure façon de démarrer un pod consiste à utiliser une construction de niveau supérieur telle que le Replication Controller, ReplicaSet, Deployment ou DeploymentConfig.

Un Replication Controller ou ReplicaSet garantit qu'un nombre spécifié de "replicas" de pod sont en cours d'exécution. Contrairement aux pods créés manuellement, les pods gérés par un Replication Controller sont automatiquement remplacés s'ils échouent, sont supprimés ou sont arrêtés.

Un Deployment fournit des mises à jour déclaratives pour les pods et les contrôleurs de réplication. Il vous suffit de décrire l'état souhaité dans un objet Deployment, et le contrôleur de Deployment changera l'état réel en l'état souhaité à un rythme contrôlé pour vous. Vous pouvez utiliser les Deployments pour :
- Créez un Deployment pour faire apparaître un Replication Controller et des pods.
- Vérifiez l'état d'un Deployment pour voir s'il réussit ou non.
- Plus tard, mettez à jour ce Deployment pour recréer les pods (par exemple, pour utiliser une nouvelle image ou configuration).
- Retour à une révision de Deployment antérieure si le Deployment actuel n'est pas stable.
- Mettre en pause et reprendre un Deployment.

Créez d'abord un déploiement à l'aide de oc (ou kubectl), l'outil CLI (client) de OpenShift / Kubernetes (https://kubernetes.io/fr/docs/reference/kubectl/[kubectl] et https://access.redhat.com/documentation/en-us/openshift_container_platform/4.12/html-single/cli_tools/index#cli-getting-started[oc]) :

[source, bash, subs="normal,attributes"]
----
$ *oc create -f frontend-deployment.yaml*
deployment.extensions/frontend-ui created
----

Vous devriez voir les instances frontend s'exécuter :

[source, bash, subs="normal,attributes"]
----
$ *oc get pods -w*
NAME                  READY     STATUS              RESTARTS   AGE
frontend-ui-?????     0/1       ContainerCreating   0          2m
frontend-ui-?????     1/1       Running             0          2m
----

Appuyez sur CTRL + C pour revenir à l'invite du shell à tout moment.

NOTE: Le statut _ContainerCreating_ signifie que Kubernetes télécharge toujours l'image depuis le registre avant de créer les conteneurs.