### Autoscaling
Duration: 5:00

OpenShift intègre une mise à l'échelle horizontale des pods basée sur l'utilisation du processeur (et des métriques personnalisées !). Nous n'aborderons que la mise à l'échelle automatique basée sur l'utilisation du processeur ici car la mise à l'échelle des métriques personnalisées et plus, longue à mettre en place.

Configurer l'autoscaling horizontal est extrêmement simple :

[source, bash, subs="normal,attributes"]
----
$ *oc autoscale deployment guestbook-service --min 1 --max 10 --cpu-percent=80*
deployment "guestbook-service" autoscaled
----

En background, OpenShift collectera périodiquement (par défaut, toutes les 30 secondes) l'utilisation du processeur et déterminera le nombre de pods nécessaires.

Vous pouvez voir l'état actuel de l'autoscaler à l'aide de la commande describe :

[source, bash, subs="normal,attributes"]
----
$ *oc describe hpa guestbook-service*
Name:				guestbook-service
Namespace:			myproject
Labels:				<none>
Annotations:			<none>
CreationTimestamp:		Thu, 04 Aug 2016 06:59:05 -0400
Reference:			Deployment/guestbook-service
Target CPU utilization:		80%
Current CPU utilization:	<unset>
Min replicas:			1
Max replicas:			10
ReplicationController pods:	1 current / 1 desired
Events:
....
----

Il va être un peu difficile d'activer les métriques de cluster et de générer la charge nécessaire pour lancer l'autoscaler. Nous ne ferons pas dans ce lab ... en fait, si nous avons le temps, nous le ferons :).

En savoir plus sur l'autoscaling horizontal des pods (HPA) dans le https://docs.openshift.com/container-platform/3.11/dev_guide/pod_autoscaling.html[guide]
