### Gérer les secrets
Duration: 20:00

ConfigMap est idéal pour stocker des configurations textuelles. Selon vos cas d'utilisation, ce n'est peut-être pas le meilleur endroit pour stocker vos informations d'identification (qui peuvent parfois être un fichier binaire plutôt que du texte).

Les secrets peuvent être utilisés pour conserver des informations sensibles, telles que des mots de passe, des jetons OAuth et des clés SSH. Les entrées dans Secrets sont encodées en Base64 . Cependant, les secrets ne sont pas chiffrés non plus lorsqu'ils sont stockés dans Kubernetes.

Généralement, nous devons mettre en place d'autres outils pour garantir la sécurité des données sensibles :

- Des droits RBAC pour limiter les accès,
- Un rélérentiel de gestion des secrets (ex : Vault d'HashiCorp, Sops de mozilla, ...),
- Des pipelines d'audit du code et des images pour vérifier les failles (_password en dur par exemple_).

Dans cette section, nous allons créer un secret contenant le nom d'utilisateur et le mot de passe MySQL. Nous mettrons ensuite à jour le contrôleur de réplication MySQL et le service de livre d'or pour faire référence aux mêmes informations d'identification.

Tout d'abord, créons un secret avec nom d'utilisateur et mot de passe sur la ligne de commande :

[source, bash, subs="normal,attributes"]
----
$ *oc create secret generic mysql-secret \
       --from-literal=username=app --from-literal=password=1337*
secret "mysql-secret" created
----

Si vous examinez le secret créé, vous verrez que les valeurs sont encodées en Base64 :

[source, bash, subs="normal,attributes"]
----
$ *oc edit secret mysql-secret*
# HINT: Type ':wq' to exit from vi
----

In the Editor, you'll see:

[source, yaml, subs="normal,attributes"]
----
apiVersion: v1
data:
  password: MTMzNw==
  username: YXBw
kind: Secret
...
----

Dans les pods, vous pouvez accéder à ces valeurs de plusieurs manières :

* Montez chaque entrée sous forme de fichier sous un répertoire (similaire à ce que nous avons fait avec ConfigMap)
* Utilisez http://kubernetes.io/docs/user-guide/downward-api/#exposing-pod-information-into-a-container[Downward API] pour exposer chaque entrée en tant que variable d'environnement (ce que vous pouvez également faire avec ConfigMap).

Étant donné que le conteneur MySQL s'attend déjà à ce que le nom d'utilisateur et le mot de passe soient configurés à l'aide des variables d'environnement, nous utiliserons cette dernière approche (API descendante).

Tout d'abord, dans le répertoire **openshift/** */, modifiez le fichier mysql-deployment.yaml. Editez le déploiement mysql et modifiez les variables MYSQL_USER et MYSQL_PASSWORD avec les valeurs suivantes :

[source, yaml, subs="normal,attributes"]
----
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mysql
spec:
...
  template:
    spec:
      containers:
      - resources:
        ...
        env:
        - name: MYSQL_ROOT_PASSWORD
          value: yourpassword
        - name: MYSQL_DATABASE
          value: guestbook
        *- name: MYSQL_USER
          valueFrom:
            secretKeyRef:
              name: mysql-secret
              key: username
        - name: MYSQL_PASSWORD
          valueFrom:
            secretKeyRef:
              name: mysql-secret
              key: password*
...
----

Nous devrons également recréer le *PersistentVolumeClaim* afin de forcer MySQL à créer l'utilisateur :

[source, bash, subs="normal,attributes"]
----
$ *oc delete pvc/mysql-pvc deployment/mysql*
persistentvolumeclaim "mysql-pvc" deleted
replicationcontroller "mysql" deleted

$ *oc create -f mysql-pvc.yaml -f mysql-deployment.yaml*
persistentvolumeclaim "mysql-pvc" created
deployment "mysql" created
----

Une fois MySQL redémarré, testez la connexion en exécutant le client MySQL directement dans le pod. Rappelez-vous comment vous pouvez utiliser _oc rsh_ pour faire ceci :

[source, bash, subs="normal,attributes"]
----
$ *oc get pods*
NAME                              READY     STATUS    RESTARTS   AGE
...
mysql-...                         1/1       Running   0          2m
...

$ *oc rsh mysql-...*
sh-4.2$ *mysql -u app -p -h 127.0.0.1*
Enter password: *1337*
Welcome to the MySQL monitor.  Commands end with ; or \g.
Your MySQL connection id is 3
Server version: 5.6.24 MySQL Community Server (GPL)

Copyright (c) 2000, 2015, Oracle and/or its affiliates. All rights reserved.

Oracle is a registered trademark of Oracle Corporation and/or its
affiliates. Other names may be trademarks of their respective
owners.

Type 'help;' or '\h' for help. Type '\c' to clear the current input statement.

mysql> *exit*
Bye
sh-4.2$ *exit*
exit
----

Super! Maintenant, MySQL récupère les informations d'identification du secret.

Ensuite, configurez le service de livre d'or et mettez également à jour les variables d'environnement.

Modifiez maintenant le déploiement du service de livre d'or et ajoutez quelques variables d'environnement :

[source, yaml, subs="normal,attributes"]
----
apiVersion: apps/v1
kind: Deployment
...
spec:
  ...
  template:
  ...
    spec:
      …
      containers:
      - image: rafabene/microservices-guestbook:1.0
        *env:
        - name: DATASOURCE_USERNAME
          valueFrom:
            secretKeyRef:
              name: mysql-secret
              key: username
        - name: DATASOURCE_PASSWORD
          valueFrom:
            secretKeyRef:
              name: mysql-secret
              key: password*
...
----

Une fois le déploiement terminé, vérifiez que l'application fonctionne toujours.